### ISSUE TITLE
feat: Migrate Expo from SDK 36 to SDK 39

### ISSUE THREAD

**Issue by pupupulp** [pupupulp/unpayd-app#5]
Hi,

Currently, the Expo SDK used in the app was 36.

It would be nice if the Expo SDK was to be updated to the latest version, SDK 39, and still render the app useable by resolving any breaking changes and such.

Happy Coding!

**Comment by Adeee11** [comment]
Hi @pupupulp can i work on this issue ?

**Comment by pupupulp** [comment]
Hi @Adeee11 ,

Sure I'll assign it to you 😁😁😁_

**Comment by pupupulp** [comment]
Hi @Adeee11 ,

Thank you for your contribution! I've already merged your changes :D :D :D

**Comment by pupupulp** [comment]
@all-contributors please add @Adeee11 for code and test
